spring:
  profiles:
    active:
      - dev
---
server:
 port: 8082

spring:
 application:
   name: xmc-shop-email
 profiles: dev
 rabbitmq:
   host: 127.0.0.1
   port: 5672
   username: guest
   password: guest
   publisher-confirms: true
   virtual-host: /
 mail:
   host: smtp.163.com
   username: zjy1997714@163.com
   password: SOQVWBBNKVXGMRPN
   enable:  true
   smtp:
     auth: true
   starttls:
     enable: true
     required: true

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://root:root@eureka1:7001/eureka
  instance:
    instance-id: xmc-shop-email-01
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 30  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: xmc-shop-email-01
  company.name: bbu
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
  endpoints:
    web:
      exposure:
        include: '*'
        


---
server:
 port: 8083
spring:
 application:
   name: xmc-shop-email
 profiles: beta
 rabbitmq:
   host:127.0.0.1
   port:5672
   username:guest
   password:guest
   publisher-confirms:true
   virtual-host:/
 mail:
   host: smtp.163.com
   username: zjy1997714@163.com
   password: SOQVWBBNKVXGMRPN
   enable:  true
   smtp:
     auth: true
   starttls:
     enable: true
     required: true


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://root:root@eureka1:7002/eureka
  instance:
    instance-id: xmc-shop-email-01
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5  # 如果现在超过了5秒的间隔（默认是90秒）

info:
  app.name: xmc-shop-email
  company.name: bbu
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

management:
   endpoints:
      web:
         exposure:
            include: '*'
