spring:
  profiles:
    active:
      - dev
---
server:
  port: 9501
spring:
  application:
    name:  xmc-shop-zuul
  profiles: dev
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://root:root@eureka1:7001/eureka
    #register-with-eureka: false
  instance:
    instance-id: xmc-shop-zuul
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
zuul:
  host:
    connect-timeout-millis: 15000 #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000   #socket超时
  #zuul的代理路径
  routes:
    xmc-shop-member: /member-proxy/**
  ignored-services:
    "*"
  prefix: /xmc-shop
  sensitive-headers: 
    - Cookie,Set-Cookie,Authorization  
ribbon:        #设置ribbon的超时时间小于zuul的超时时间
  ReadTimeout: 10000
  ConnectTimeout: 10000
